/*WEIGHT GAIN IN CHICKENS BY TYPE OF FEED*/

DATA FERTILIZER;  		/*DATASET NAME*/
	INPUT FEEDTYPE  	/* FIELD NAMES */
		  WEIGHTGAIN;
	DATALINES;
	1 46.20
	1 55.60
	1 53.30
	1 44.80
	1 55.40
	1 56.00
	1 48.90
	2 51.30
	2 52.40
	2 54.60
	2 52.20
	2 64.30
	2 55.00
	;
RUN;

ODS HTML;
	PROC SORT          /* SORTING THE DATASET BY FIELD */
		DATA = FERTILIZER; /*DATASET NAME*/
		BY FEEDTYPE ;	   /*GROUPING BY FIELD NAME*/
	RUN;
ODS HTML CLOSE;

PROC MEANS 			   /* CALCULATING THE MEANS */
	DATA = fertilizer; /* USING DATASET */
	VAR WEIGHTGAIN;    /* USED TO SPLIT DATA INTO GROUPS*/
	BY FEEDTYPE;	
	TITLE 'Summary statistics by group'; /*SHOWS A STRING AT THE TOP OF THE TABLE*/
RUN;

ODS HTML;			/* THE OUTPUT DISPLAY SYSTEM WE ARE USING IS HTML*/
	PROC PRINT 
		DATA = fertilizer;
	RUN;
ODS HTML CLOSE;

PROC MEANS 
	DATA = fertilizer; 
	VAR WEIGHTGAIN; 
	CLASS FEEDTYPE; /* USED FOR GROUP DATA INTERNALLY*/
	TITLE 'Summary statistics USING CLASS';
RUN;

ODS HTML;
	PROC PRINT 
		DATA = fertilizer;
	RUN;
ODS HTML CLOSE;
