/*A CERTAIN MEDICAL IMPLANT COMPONENT IS REPORTED TO BE 4CM IN LENGTH
BY IT'S MANUFACTURER*/


DATA ONESAMPLE;
INPUT LENGTH @@;
DATALINES;
4 3.95 4.01 3.95 4 
3.98 3.97 3.97 4.01 
3.98 3.99 4.01 4.02 
4.02 3.98
;
RUN;

ODS HTML;
PROC PRINT DATA = ONESAMPLE;
RUN;
ODS HTML CLOSE;


ODS HTML;
ODS GRAPHICS ON;
Title 'Single sample t-test, using PROC UNIVARIATE';
PROC UNIVARIATE DATA = ONESAMPLE MU0=4;
VAR LENGTH;
RUN;
ODS GRAPHICS OFF;
ODS HTML CLOSE;


ODS HTML;
ODS GRAPHICS ON;
Title 'Single sample t-test using PROC TTEST';
PROC TTEST DATA = ONESAMPLE  H0=4;
VAR LENGTH;
RUN;
ODS GRAPHICS OFF;
ODS HTML CLOSE;
