/*A BIOLOGIST EXPERIMENTING WITH PLANT GROWTH DESIGNS AN EXPERIMENT IN WHICH 
15 SEEDS ARE RANDOMLY ASSIGNED TO ONE OF TWO FERTILIZERS AND THE HEIGHT OF THE RESULTING
PLANT IS MEASURED AFTER TWO WEEKS*/


DATA TTEST;
INPUT BRAND $ HEIGHT;
DATALINES;
   A   20.00
   A   23.00
   A   32.00
   A   24.00
   A   25.00
   A   28.00
   A   27.50
   B   25.00
   B   46.00
   B   56.00
   B   45.00
   B   46.00
   B   51.00
   B   34.00
   B   47.50
;
RUN;

ODS HTML;
PROC PRINT DATA = TTEST;
RUN;
ODS HTML CLOSE;


ODS HTML;
ODS GRAPHICS ON;
PROC TTEST DATA = TTEST;
     CLASS BRAND; 
     VAR HEIGHT;
     Title 'Independent Group t-Test Example';
RUN;
ODS GRAPHICS OFF;
ODS HTML CLOSE;
